# These are supported funding model platforms

github: #sscornelius
patreon: # digitstar
open_collective: # digitalstarworld
ko_fi: # sscornelius
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # sscornelius
polar: # Replace with a single Polar username
buy_me_a_coffee: rockstar
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
